"""Run every evaluation, write backend/artifacts/metrics/*.json and docs/EVALUATION_REPORT.md."""
import json
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from app import config as C, data, evaluation as E  # noqa: E402

ROOT = C.BACKEND.parent


def dump(name, obj):
    (C.METRICS / f"{name}_metrics.json").write_text(json.dumps(obj, indent=2, default=str))


def pct(x):
    return "n/a" if x is None else f"{x * 100:.1f}%"


def report(fc, det, bn, pr, sim):
    L = ["# FlowSense AI — Evaluation Report", "",
         "Auto-generated by `backend/scripts/evaluate_models.py`. Raw numbers: `backend/artifacts/metrics/*.json`.",
         "Labels: **Validation** = held-out organizer data; **Simulation Estimate** = our model's output with no ground truth.",
         "", "## 1. Forecasting — Validation",
         f"Ground truth: `forecast_targets_validation.csv` (labels only), {fc['anchors']} anchors x {fc['segments']} segments. "
         f"Models trained on train days 1-12; residual bands from days 13-15. Share of anchor rows in a congested state: {pct(fc['congested_share'])}.", "",
         "| Target | Model MAE | Persistence MAE | Δ MAE | Model RMSE | Persistence RMSE | P10–P90 coverage | Congested-only MAE (model / persistence) |",
         "|---|---|---|---|---|---|---|---|"]
    for k, r in fc["results"].items():
        cg = r["congested_slots"]
        L.append(f"| {k} | {r['model']['mae']:.4f} | {r['persistence']['mae']:.4f} | {r['mae_improvement_pct']:+.1f}% | "
                 f"{r['model']['rmse']:.4f} | {r['persistence']['rmse']:.4f} | {pct(r['p10_p90_coverage'])} | "
                 f"{cg['model']['mae']:.4f} / {cg['persistence']['mae']:.4f} |")
    L += ["", "Speed MAPE (model / persistence): " + ", ".join(
        f"{k}: {r['model']['mape_pct']:.2f}% / {r['persistence']['mape_pct']:.2f}%" for k, r in fc["results"].items() if k.startswith("speed")),
          "", "The P10–P90 band is an empirical residual band, not a calibrated probabilistic forecast; nominal coverage is 80%.", ""]
    L += ["## 2. Detection — Validation", f"Detector `{det['detector']}`, threshold {det['threshold']:.3f} (speed-ratio units), selected on incidents_train only.",
          f"Positive = {det['positive_definition']}. Roadwork slots excluded from scoring.", "",
          "| Split | Slot P | Slot R | Slot F1 | FP slots/day | Incidents detected | Median delay (min) | Unmatched events/day |", "|---|---|---|---|---|---|---|---|"]
    for sp, e in det["splits"].items():
        s, ev = e["slot_level"], e["event_level"]
        L.append(f"| {sp} | {s['precision']:.3f} | {s['recall']:.3f} | {s['f1']:.3f} | {s['false_positive_slots_per_day']:.1f} | "
                 f"{ev['incidents_detected']}/{ev['incidents']} | {ev['median_detection_delay_min']} | {ev['unmatched_events_per_day']:.1f} |")
    L += ["", det["note"], "", "### Incident-type diagnosis"]
    for sp, e in det["splits"].items():
        td = e.get("type_diagnosis")
        if td:
            L.append(f"- **{sp}**: accuracy {pct(td['accuracy'])} on {td['evaluated_on_detected_incidents']} detected incidents "
                     f"(UNKNOWN returned {pct(td['unknown_rate'])}; uniform chance over 5 types = 20%). "
                     f"Per type: {td['per_type']}. Absent from this split: {', '.join(td['types_absent_from_this_split']) or 'none'}.")
    L += ["", "Type likelihood is weak by design: in this data severity, not type, drives the traffic signature. The UI shows it as low-confidence.", ""]
    L += ["## 3. Recurring bottlenecks — benchmark vs organizer flag", f"Method: {bn['method']} (organizer flag and `peak_capacity_factor` not used).", "",
          f"- Detected {bn['n_detected']}, reference {bn['n_reference']}: precision {bn['precision']:.3f}, recall {bn['recall']:.3f}, F1 {bn['f1']:.3f}",
          f"- Segments recovered: {', '.join(bn['segments_recovered']) or 'none'}",
          f"- Ranking AUC of the detector score vs. the flag: {bn['ranking_auc']:.3f}; reference segments in the detector's top 16: {bn['reference_in_top_16']}/16",
          "", "| z threshold | flagged | P | R | F1 |", "|---|---|---|---|---|"]
    for z, s in bn["sensitivity_by_threshold_label_informed"].items():
        L.append(f"| {z} | {s['n_flagged']} | {s['precision']:.2f} | {s['recall']:.2f} | {s['f1']:.2f} |")
    L += ["", bn["note"], ""]
    L += ["## 4. Propagation — indirect validation", pr["evaluation"] + ".", "",
          f"- Prediction issued at {pr['prediction_issued']}; affected = {pr['affected_definition']}",
          f"- Neighbor hit rate (precision) {pct(pr['neighbor_hit_rate_precision'])}, recall {pct(pr['neighbor_recall'])}, false propagation rate {pct(pr['false_propagation_rate'])} (tp {pr['tp']}, fp {pr['fp']}, fn {pr['fn']})",
          f"- Control base rate (same neighbors, same clock time, other days): {pct(pr['control_base_rate'])}",
          f"- Calibrated from train: decay {pr['calibration']['decay']}, lag per hop {pr['calibration']['lag_min_per_hop']} min", ""]
    L += ["## 5. Simulation — Simulation Estimate (no ground truth)", sim["label"] + ".", "",
          f"- All assigned paths respect turn restrictions: {sim['checks']['all_assigned_paths_respect_turn_restrictions']}",
          f"- Share of validation incidents whose simulated capacity loss increases network delay: {pct(sim['checks']['incident_increases_network_delay_share'])}", ""]
    L += ["Raw OD assignment vs. observed flow (why the pivot-point method is used):", "",
          "| Time | Demand scale | Flow corr. (raw assignment vs observed) | Relative gap | Over-capacity links raw / observed |", "|---|---|---|---|---|"]
    for b in sim["baseline_fit"]:
        L.append(f"| {b['time']} | {b['demand_scale']} | {b['raw_assignment_flow_correlation_vs_observed']:.3f} | {b['relative_gap']:.4f} | "
                 f"{b['over_capacity_links_raw_assignment']} / {b['over_capacity_links_observed']} |")
    L += ["", "Simulated incident impact on validation incidents (pivot-point; capacity reduction by labelled severity — evaluation only):", "",
          "| Segment | Time | Capacity reduction | Network delay change | Within solver tolerance | Segments worsened | Direct candidate |", "|---|---|---|---|---|---|---|"]
    for s in sim["scenario_deltas"]:
        L.append(f"| {s['incident_segment']} | {s['time']} | {s['capacity_reduction']:.0%} | {s['incident_delay_change_pct']:+.3f}% | "
                 f"{s['within_solver_tolerance']} | {s['segments_worsened']} | {s['direct_candidate']} |")
    L += ["", "The static OD table reproduces the observed flow pattern poorly, so scenarios are pivoted on the observed flows at t: "
          "scenario flow = observed + (assigned scenario − assigned reference). Network-wide deltas from a single-segment change are small; "
          "where they are below the Frank-Wolfe gap bound they are flagged 'within solver tolerance' and the UI leads with local effects.", ""]
    (ROOT / "docs" / "EVALUATION_REPORT.md").write_text("\n".join(L), encoding="utf-8")


def main():
    t0 = time.time()
    p = data.full_panel()
    fc = E.forecast_metrics(p); dump("forecast", fc); print(f"forecast done {time.time() - t0:.0f}s")
    det = E.detection_metrics(p); dump("detection", det); print("detection done")
    bn = E.bottleneck_metrics(); dump("bottleneck", bn); print("bottleneck done")
    pr = E.propagation_metrics(p); dump("propagation", pr); print("propagation done")
    sim = E.simulation_metrics(p); dump("simulation", sim); print("simulation done")
    report(fc, det, bn, pr, sim)
    print(f"EVALUATION_REPORT.md written ({time.time() - t0:.0f}s)")


if __name__ == "__main__":
    main()
