"""Synthetic robustness evaluation -> backend/artifacts/metrics/robustness_metrics.json + docs/ROBUSTNESS_REPORT.md."""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from app import config as C, robustness  # noqa: E402

KEYS = [("forecast_mae_speed_15m", "Speed MAE +15m", 3), ("forecast_mae_flow_15m", "Flow MAE +15m", 1),
        ("forecast_mae_congestion_60m", "Congestion MAE +60m", 4), ("detection_f1", "Detection F1", 3),
        ("false_positive_slots_per_day", "FP slots/day", 1), ("incidents_detected", "Incidents detected", None),
        ("mean_data_quality", "Mean data quality", 3), ("mean_confidence_on_incidents", "Confidence on incidents", 3)]


def fmt(v, d):
    if v is None:
        return "—"
    return v if d is None else f"{v:.{d}f}"


def main():
    res = robustness.run()
    (C.METRICS / "robustness_metrics.json").write_text(json.dumps(res, indent=2, default=str))
    L = ["# FlowSense AI — Robustness Report", "",
         f"**{res['label']}.** Generated by `backend/scripts/run_robustness.py`; raw numbers in `backend/artifacts/metrics/robustness_metrics.json`.", "",
         f"- Slice: {res['slice'][0]} → {res['slice'][1]} (first day = feature history); scored days {res['scored_days'][0]} → {res['scored_days'][1]} (validation).",
         f"- Corruption applied to an in-memory copy at rate {res['corruption_rate']:.0%} (seed {res['seed']}). Raw organizer files are never modified.",
         "- **Sanitized** = the production pipeline (`data.sanitize`: sort/reindex, de-duplicate, reject negatives / impossible values / spikes / stuck runs, forward-fill ≤ 15 min).",
         "- **Naive** = the same models on the uncleaned grid (last duplicate wins, bad values kept). It exists only to show what sanitization contributes.", "",
         "| Corruption | Pipeline | " + " | ".join(k[1] for k in KEYS) + " |", "|---|---|" + "---|" * len(KEYS)]
    for kind, row in res["runs"].items():
        for pipe in ("sanitized", "naive"):
            if pipe not in row:
                continue
            r = row[pipe]
            if "pipeline_failure" in r:
                L.append(f"| {kind} | {pipe} | PIPELINE FAILURE: {r['pipeline_failure']} |" + " |" * (len(KEYS) - 1))
                continue
            L.append(f"| {kind} | {pipe} | " + " | ".join(str(fmt(r.get(k), d)) for k, _, d in KEYS) + " |")
    L += ["", "## Sanitizer actions per corruption", ""]
    for kind, row in res["runs"].items():
        if "sanitizer_report" in row:
            L.append(f"- **{kind}**: {row['sanitizer_report']}")
    L += ["", "## Reading the table", "",
          "- Confidence is multiplied by per-segment data quality (share of accepted original readings in the last hour), so "
          "corrupted inputs lower the confidence shown to the operator instead of silently producing the same certainty.",
          "- Forecast MAE is computed on every 4th validation anchor of the scored days against `forecast_targets_validation.csv` (labels only).",
          "- Detection metrics follow the slot-level definition in EVALUATION_REPORT.md.",
          "- This does not reproduce the hidden test set's noise; it measures behaviour under the noise *types* the manifest names.", ""]
    (C.BACKEND.parent / "docs" / "ROBUSTNESS_REPORT.md").write_text("\n".join(L), encoding="utf-8")
    print("ROBUSTNESS_REPORT.md written")


if __name__ == "__main__":
    main()
